name: streamlit
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9.12
 - pip
 - pip:
   - streamlit
   - pandas
   - pyodbc
   - matplotlib
   - numpy
   - datetime
   - plotly